export let keywords = [
    "anti-national",
    "no-nrc",
    "protest",
    "state against centre",
    "Anti-Citizenship Act",
    "student protests",
    "bjp destroys",
    "sedition",
    "intersectoral issues",
    "increasing covid cases",
    "centre failed",
    "side effects of demonetisation",
    "unemployment",
    "falling gdp",
    "broken state of education",
    "Arnab Goswami Arrested, Union Ministers Came Out in Support",
    "corruption",
    "economic justice",
    "falling democracy",
    "falling gdp",
    "Modi-Shah Ashwamedha yagna demolished the NDA ",
    "How Modi has made a ‘Nehruvian’ half-blunder ",
    "विरोधकर्ता",
    "विरोध",
    "सवाल",
    "Pollution",
    "लापरवाही",
    "Delhi में ICU Bed की हो रही कमी",
    "काम नहीं मिल रहा",
    "Yogi सरकार की अंधेरगर्दी",
    "केंद्र के समाधान को ठुकराया",
    "GST गतिरोध जारी",
    "कपिल सिब्बल का निर्मला सीतारमण पर तंज",
    "क्यों चुप हैं प्रधानमंत्री, वित्त मंत्री?",
    "बीजेपी और कांग्रेस के बीच वार-पलटवार",
    "प्रवासी श्रमिकों की हालत पर सियासत",
    "अर्थव्यवस्था का बाइस्कोप - GDP को छोड़िए, जेब में देखिए",
    "बहुत नाइंसाफी",
    "Decoding Nirmala Sitharaman's Bihar Election Announcement",
    "BJP to lose",
    "worst government",
    "worst pm",
    "dystopia in India’s democracy",
    "liberal outrage",
    "Liberal angst",
    "Dystopian Democracy",
    "disinvestment plans for Air India",
    "decreased funding for public universities",
    "bifurcation of democracy",
    "state of crisis in country due to modi government",
    "dystopian future where Hindu nationalists take over",
    "surge in child trafficking",
    "No Central Data on Health Workers Who Died",
    "Fiscal mismanagement threatens India’s economic recovery",
    "threatens India’s economic recovery",
    "Why Haryana and Punjab farmers are angry",
    "farmers are angry",
    "rural consumption may not drive up growth",
    "no growth",
    "How a series of economic misadventures derailed India’s growth story",
    "Conquering the Great Divide",
    "dividing society",
    "divide and conquer",
    "India reluctant to provide unemployment allowance",
    "Government reluctant to provide unemployment allowance",
    "India's food insecurity",
    "BMC faces flak as workers ‘denied drinking water, access to toilets for being Dalit’",
    "laws against dalit",
    "Minor girl gang-raped",
    "protest against unregularised wages",
    "ASHA workers go on strike",
    "Coronavirus cases surge among factory workers in post-lockdown India",
    "Modi’s Covid-19 policies make clear that in India some lives matter more than others",
    "What NEP 2020 Offers Is A Fatal Illusion Of Choice",
    "Dynast Within A Democracy",
    "The Bihar Polls Were Devoid Of Real Choices",
    "devoid of real choices",
    "Against Vaccine Nationalism",
    "Poor Working Conditions",
    "AYUSH Doctors Strike",
    "press freedom",
    "bjp vs shiv sena",
    "Shiv Sena-BJP fight",
    "Sudhir Chaudhary Supports Arnab Goswami",
    "i support arnab",
    "Government of India",
    "freedom of expression",
];



